# Generated by tools/generate_golden_tests.R -- edit that script, not this file.
# Each metric set is computed once here and reused by the test_*.R files.

sampdat <- phabformat(sampdat)

algaemet <- suppressWarnings(algae(sampdat))
bankmorphmet <- suppressWarnings(bankmorph(sampdat))
bankstabilitymet <- suppressWarnings(bankstability(sampdat))
channelmorphmet <- suppressWarnings(channelmorph(sampdat))
channelsinuositymet <- suppressWarnings(channelsinuosity(sampdat))
densiometermet <- suppressWarnings(densiometer(sampdat))
disturbancemet <- suppressWarnings(disturbance(sampdat))
flowmet <- suppressWarnings(flow(sampdat))
habitatmet <- suppressWarnings(habitat(sampdat))
miscmet <- suppressWarnings(misc(sampdat))
qualitymet <- suppressWarnings(quality(sampdat))
ripvegmet <- suppressWarnings(ripveg(sampdat))
submet <- suppressWarnings(substrate(sampdat))
