# Golden-value regression tests for bankstability().
# Generated by tools/generate_golden_tests.R -- regenerate rather than hand-editing.
# Expected values are the confirmed-correct output for `sampdat` as of 2026-08-20.

test_that('bankstability() returns the expected samples in the expected order', {
  expect_equal(rownames(bankstabilitymet), c('105PS0231_2013-08-29_DFW-ABL', '205PS0202_2013-07-17_MPSL-DFW', '308PS0204_2013-05-21_DFW-ABL', '520PS0455_2013-07-22_MPSL-DFW'))
})

test_that('bankstability() returns the expected columns', {
  expect_equal(colnames(bankstabilitymet), c('PBM_S.result', 'PBM_S.count', 'PBM_V.result', 'PBM_V.count', 'PBM_E.result', 'PBM_E.count'))
})

test_that('Checking PBM_S.result', {
  expect_equal(as.vector(bankstabilitymet[, "PBM_S.result"]), c(0, 5, 82, 0))
})

test_that('Checking PBM_S.count', {
  expect_equal(as.vector(bankstabilitymet[, "PBM_S.count"]), c(22, 22, 22, 22))
})

test_that('Checking PBM_V.result', {
  expect_equal(as.vector(bankstabilitymet[, "PBM_V.result"]), c(77, 9, 14, 91))
})

test_that('Checking PBM_V.count', {
  expect_equal(as.vector(bankstabilitymet[, "PBM_V.count"]), c(22, 22, 22, 22))
})

test_that('Checking PBM_E.result', {
  expect_equal(as.vector(bankstabilitymet[, "PBM_E.result"]), c(23, 86, 5, 9))
})

test_that('Checking PBM_E.count', {
  expect_equal(as.vector(bankstabilitymet[, "PBM_E.count"]), c(22, 22, 22, 22))
})

