# Golden-value regression tests for quality().
# Generated by tools/generate_golden_tests.R -- regenerate rather than hand-editing.
# Expected values are the confirmed-correct output for `sampdat` as of 2026-08-20.

test_that('quality() returns the expected samples in the expected order', {
  expect_equal(rownames(qualitymet), c('308PS0204_2013-05-21_DFW-ABL', '205PS0202_2013-07-17_MPSL-DFW', '520PS0455_2013-07-22_MPSL-DFW', '105PS0231_2013-08-29_DFW-ABL'))
})

test_that('quality() returns the expected columns', {
  expect_equal(colnames(qualitymet), c('XWAT.result', 'XWDO.result', 'XWPH.result', 'XWSL.result', 'XWSC.result', 'XWTC.result', 'XWTF.result', 'XWTB.result', 'XWAT.count', 'XWDO.count', 'XWPH.count', 'XWSL.count', 'XWSC.count', 'XWTC.count', 'XWTF.count', 'XWTB.count', 'XWAT.sd', 'XWDO.sd', 'XWPH.sd', 'XWSL.sd', 'XWSC.sd', 'XWTC.sd', 'XWTF.sd', 'XWTB.sd'))
})

test_that('Checking XWAT.result', {
  expect_equal(as.vector(qualitymet$XWAT.result), c(140, 230, 80, 195))
})

test_that('Checking XWDO.result', {
  expect_equal(as.vector(qualitymet$XWDO.result), c(15.2, 9.04, 8.79, 8.97))
})

test_that('Checking XWPH.result', {
  expect_equal(as.vector(qualitymet$XWPH.result), c(NaN, 8.02, 7.83, 7.99))
})

test_that('Checking XWSL.result', {
  expect_equal(as.vector(qualitymet$XWSL.result), c(0.2, 0.56, 0.05, 0.2))
})

test_that('Checking XWSC.result', {
  expect_equal(as.vector(qualitymet$XWSC.result), c(317.3, 1129, 117, 423.5))
})

test_that('Checking XWTC.result', {
  expect_equal(as.vector(qualitymet$XWTC.result), c(15.2, 15.5, 22.4, 14.7))
})

test_that('Checking XWTF.result', {
  expect_equal(as.vector(qualitymet$XWTF.result), c(59.4, 59.9, 72.3, 58.5))
})

test_that('Checking XWTB.result', {
  expect_equal(as.vector(qualitymet$XWTB.result), c(0.8, 3.05, 4.68, NaN))
})

test_that('Checking XWAT.count', {
  expect_equal(as.vector(qualitymet$XWAT.count), c(1, 1, 1, 1))
})

test_that('Checking XWDO.count', {
  expect_equal(as.vector(qualitymet$XWDO.count), c(1, 1, 1, 1))
})

test_that('Checking XWPH.count', {
  expect_equal(as.vector(qualitymet$XWPH.count), c(0, 1, 1, 1))
})

test_that('Checking XWSL.count', {
  expect_equal(as.vector(qualitymet$XWSL.count), c(1, 1, 1, 1))
})

test_that('Checking XWSC.count', {
  expect_equal(as.vector(qualitymet$XWSC.count), c(1, 1, 1, 1))
})

test_that('Checking XWTC.count', {
  expect_equal(as.vector(qualitymet$XWTC.count), c(1, 1, 1, 1))
})

test_that('Checking XWTF.count', {
  expect_equal(as.vector(qualitymet$XWTF.count), c(1, 1, 1, 1))
})

test_that('Checking XWTB.count', {
  expect_equal(as.vector(qualitymet$XWTB.count), c(1, 1, 1, 0))
})

test_that('Checking XWAT.sd', {
  expect_equal(as.vector(qualitymet$XWAT.sd), c(NA_real_, NA_real_, NA_real_, NA_real_))
})

test_that('Checking XWDO.sd', {
  expect_equal(as.vector(qualitymet$XWDO.sd), c(NA_real_, NA_real_, NA_real_, NA_real_))
})

test_that('Checking XWPH.sd', {
  expect_equal(as.vector(qualitymet$XWPH.sd), c(NA_real_, NA_real_, NA_real_, NA_real_))
})

test_that('Checking XWSL.sd', {
  expect_equal(as.vector(qualitymet$XWSL.sd), c(NA_real_, NA_real_, NA_real_, NA_real_))
})

test_that('Checking XWSC.sd', {
  expect_equal(as.vector(qualitymet$XWSC.sd), c(NA_real_, NA_real_, NA_real_, NA_real_))
})

test_that('Checking XWTC.sd', {
  expect_equal(as.vector(qualitymet$XWTC.sd), c(NA_real_, NA_real_, NA_real_, NA_real_))
})

test_that('Checking XWTF.sd', {
  expect_equal(as.vector(qualitymet$XWTF.sd), c(NA_real_, NA_real_, NA_real_, NA_real_))
})

test_that('Checking XWTB.sd', {
  expect_equal(as.vector(qualitymet$XWTB.sd), c(NA_real_, NA_real_, NA_real_, NA_real_))
})

