# Golden-value regression tests for densiometer().
# Generated by tools/generate_golden_tests.R -- regenerate rather than hand-editing.
# Expected values are the confirmed-correct output for `sampdat` as of 2026-08-20.

test_that('densiometer() returns the expected samples in the expected order', {
  expect_equal(rownames(densiometermet), c('105PS0231_2013-08-29_DFW-ABL', '205PS0202_2013-07-17_MPSL-DFW', '308PS0204_2013-05-21_DFW-ABL', '520PS0455_2013-07-22_MPSL-DFW'))
})

test_that('densiometer() returns the expected columns', {
  expect_equal(colnames(densiometermet), c('XCDENMID.result', 'XCDENMID.count', 'XCDENMID.sd', 'XCDENBK.result', 'XCDENBK.count', 'XCDENBK.sd'))
})

test_that('Checking XCDENMID.result', {
  expect_equal(as.vector(densiometermet[, "XCDENMID.result"]), c(6, 98, 81, 15))
})

test_that('Checking XCDENMID.count', {
  expect_equal(as.vector(densiometermet[, "XCDENMID.count"]), c(44, 44, 44, 44))
})

test_that('Checking XCDENMID.sd', {
  expect_equal(as.vector(densiometermet[, "XCDENMID.sd"]), c(18.8, 5.3, 17.1, 30))
})

test_that('Checking XCDENBK.result', {
  expect_equal(as.vector(densiometermet[, "XCDENBK.result"]), c(67, NaN, 97, 90))
})

test_that('Checking XCDENBK.count', {
  expect_equal(as.vector(densiometermet[, "XCDENBK.count"]), c(22, 0, 22, 22))
})

test_that('Checking XCDENBK.sd', {
  expect_equal(as.vector(densiometermet[, "XCDENBK.sd"]), c(33.2, NA_real_, 8.8, 24.5))
})

