# Golden-value regression tests for flow().
# Generated by tools/generate_golden_tests.R -- regenerate rather than hand-editing.
# Expected values are the confirmed-correct output for `sampdat` as of 2026-08-20.

test_that('flow() returns the expected samples in the expected order', {
  expect_equal(rownames(flowmet), c('308PS0204_2013-05-21_DFW-ABL', '205PS0202_2013-07-17_MPSL-DFW', '520PS0455_2013-07-22_MPSL-DFW', '105PS0231_2013-08-29_DFW-ABL'))
})

test_that('flow() returns the expected columns', {
  expect_equal(colnames(flowmet), c('FL_Q_F.result', 'FL_Q_F.count', 'FL_Q_M.result', 'FL_Q_M.count', 'FL_N_M.result', 'FL_N_F.result', 'XWV_F.result', 'XWV_F.count', 'XWV_F.sd', 'XWV_M.result', 'XWV_M.count', 'XWV_M.sd', 'MWVM_F.result', 'MWVM_F.count', 'MWVM_M.result', 'MWVM_M.count', 'PWVZ.result', 'PWVZ.count'))
})

test_that('Checking FL_Q_F.result', {
  expect_equal(as.vector(flowmet$FL_Q_F.result), c(17.163, 1.202, 70.402, NA_real_))
})

test_that('Checking FL_Q_F.count', {
  expect_equal(as.vector(flowmet$FL_Q_F.count), c(12, 11, 14, 0))
})

test_that('Checking FL_Q_M.result', {
  expect_equal(as.vector(flowmet$FL_Q_M.result), c(0.486, 0.034, 1.993, NA_real_))
})

test_that('Checking FL_Q_M.count', {
  expect_equal(as.vector(flowmet$FL_Q_M.count), c(12, 11, 14, 0))
})

test_that('Checking FL_N_M.result', {
  expect_equal(as.vector(flowmet$FL_N_M.result), c(NA_real_, NA_real_, NA_real_, NA_real_))
})

test_that('Checking FL_N_F.result', {
  expect_equal(as.vector(flowmet$FL_N_F.result), c(NA_real_, NA_real_, NA_real_, NA_real_))
})

test_that('Checking XWV_F.result', {
  expect_equal(as.vector(flowmet$XWV_F.result), c(0.5, 0.24, 1.43, NaN))
})

test_that('Checking XWV_F.count', {
  expect_equal(as.vector(flowmet$XWV_F.count), c(12, 11, 14, 0))
})

test_that('Checking XWV_F.sd', {
  expect_equal(as.vector(flowmet$XWV_F.sd), c(0.461, 0.183, 0.805, NA_real_))
})

test_that('Checking XWV_M.result', {
  expect_equal(as.vector(flowmet$XWV_M.result), c(0.15, 0.07, 0.44, NaN))
})

test_that('Checking XWV_M.count', {
  expect_equal(as.vector(flowmet$XWV_M.count), c(12, 11, 14, 0))
})

test_that('Checking XWV_M.sd', {
  expect_equal(as.vector(flowmet$XWV_M.sd), c(0.14, 0.056, 0.245, NA_real_))
})

test_that('Checking MWVM_F.result', {
  expect_equal(as.vector(flowmet$MWVM_F.result), c(1.1, 0.4, 2.7, -Inf))
})

test_that('Checking MWVM_F.count', {
  expect_equal(as.vector(flowmet$MWVM_F.count), c(12, 11, 14, 0))
})

test_that('Checking MWVM_M.result', {
  expect_equal(as.vector(flowmet$MWVM_M.result), c(0.3, 0.1, 0.8, -Inf))
})

test_that('Checking MWVM_M.count', {
  expect_equal(as.vector(flowmet$MWVM_M.count), c(12, 11, 14, 0))
})

test_that('Checking PWVZ.result', {
  expect_equal(as.vector(flowmet$PWVZ.result), c(25, 18.2, 14.3, NaN))
})

test_that('Checking PWVZ.count', {
  expect_equal(as.vector(flowmet$PWVZ.count), c(12, 11, 14, 0))
})

