# Hand-maintained tests for incomplete-data handling. NOT generated by
# tools/generate_golden_tests.R -- `sampdat` is complete, so these build their
# own degraded inputs to cover the NA / -Inf / divide-by-zero paths reported by
# Nathan (2026-08-20).
#
# helper_object.R overwrites `sampdat` with its formatted version, so these
# reach for PHABMetrics::sampdat to get the raw frame.

test_that('XWDM survives a transect with no usable depth readings', {

  # -88 is the project's missing-value code; bankmorph() maps it to NA. Blanking
  # one transect used to make max(NA, na.rm = TRUE) return -Inf, which then
  # collapsed XWDM -- and anything derived from it -- to -Inf.
  raw <- PHABMetrics::sampdat
  sel <- raw$AnalyteName == 'StationWaterDepth' &
         raw$MethodName  == 'FieldMeasure' &
         raw$StationCode == '205PS0202' &
         grepl('^Tran.A', raw$LocationCode)
  expect_gt(sum(sel), 0)          # guard: the fixture must actually hit rows
  raw$Result[sel] <- -88

  bm <- suppressWarnings(bankmorph(phabformat(raw)))
  hit <- '205PS0202_2013-07-17_MPSL-DFW'

  expect_true(all(is.finite(bm$XWDM.result)))
  expect_equal(bm[hit, 'XWDM.result'], 14.1)

  # the blanked transect must drop out of the count rather than be counted as data
  expect_equal(bm[hit, 'XWDM.count'], 20)
  expect_equal(bm[setdiff(rownames(bm), hit), 'XWDM.count'], c(21, 21, 21))

  # and the derived metrics must not be poisoned
  expect_true(all(is.finite(bm$XBKF_TH.result)))
  expect_true(all(is.finite(bm$XBKF_DA.result)))

  # unaffected sites keep their baseline values
  expect_equal(bm[setdiff(rownames(bm), hit), 'XWDM.result'], c(79.8, 40.1, 77.0))
})

test_that('SINU is NA, not Inf, when a reach has no usable bearings', {

  # No bearings => cos_ + sin_ == 0 => sqrt() denominator of 0 => Inf.
  raw <- PHABMetrics::sampdat
  sel <- raw$AnalyteName == 'Bearing' & raw$StationCode == '205PS0202'
  expect_gt(sum(sel), 0)
  raw$Result[sel] <- NA

  cs <- suppressWarnings(channelsinuosity(phabformat(raw)))
  hit <- '205PS0202_2013-07-17_MPSL-DFW'

  expect_false(any(is.infinite(cs$SINU.result)))
  expect_true(is.na(cs[hit, 'SINU.result']))
  expect_equal(cs[hit, 'SINU.count'], 0)

  # other reaches unaffected
  expect_equal(cs[setdiff(rownames(cs), hit), 'SINU.result'], c(1.06, 1.13, 1.07))
})

test_that('SLOPE_0 / SLOPE_0_5 / SLOPE_1 / SLOPE_2 are NA when no slope was measured', {

  # With no usable slopes, `Length, Segment`[slope_x] is all NA and
  # sum(na.rm = TRUE) is 0, so these used to report 0 -- "0% of reach length at
  # or below this slope" -- for reaches where gradient was never recorded.
  # sampdat records Slope at two sites and Elevation Difference at the other
  # two, so dropping Slope leaves sites 2 and 3 with no gradient source.
  raw <- PHABMetrics::sampdat
  raw <- raw[!(raw$AnalyteName %in% 'Slope'), ]

  cs <- suppressWarnings(channelsinuosity(phabformat(raw)))
  gone <- c('205PS0202_2013-07-17_MPSL-DFW', '308PS0204_2013-05-21_DFW-ABL')
  kept <- setdiff(rownames(cs), gone)

  for (m in c('SLOPE_0.result','SLOPE_0_5.result','SLOPE_1.result','SLOPE_2.result')) {
    expect_true(all(is.na(cs[gone, m])), info = m)
    expect_equal(cs[gone, paste0(sub('\\.result$', '', m), '.count')], c(0, 0), info = m)
  }

  # reaches that still have a gradient source keep their values
  expect_equal(cs[kept, 'SLOPE_0_5.result'], c(100, 60))
  expect_equal(cs[kept, 'SLOPE_2.result'],   c(100, 90))
})

test_that('a measured slope percentage of 0 stays 0 and does not become NA', {

  # The guard must distinguish "measured, none qualify" from "never measured".
  # On complete sampdat, SLOPE_0 is a real 0 everywhere and 308PS0204 has a
  # real 0 for SLOPE_0_5.
  cs <- suppressWarnings(channelsinuosity(phabformat(PHABMetrics::sampdat)))

  expect_equal(as.vector(cs$SLOPE_0.result), c(0, 0, 0, 0))
  expect_false(any(is.na(cs$SLOPE_0.result)))
  expect_equal(cs['308PS0204_2013-05-21_DFW-ABL', 'SLOPE_0_5.result'], 0)
  expect_equal(as.vector(cs$SLOPE_0_5.result), c(100, 20, 0, 60))
  expect_equal(as.vector(cs$SLOPE_1.result),   c(100, 60, 40, 70))
  expect_equal(as.vector(cs$SLOPE_2.result),   c(100, 90, 70, 90))
})

test_that('XBEARING is NA, not 0, when a reach has no usable bearings', {

  # sum(p_bear, na.rm = TRUE) over an all-NA reach is 0, which used to be
  # reported as a mean bearing of 0 (due north) with an sd of 0.
  raw <- PHABMetrics::sampdat
  sel <- raw$AnalyteName == 'Bearing' & raw$StationCode == '205PS0202'
  expect_gt(sum(sel), 0)
  raw$Result[sel] <- NA

  cs <- suppressWarnings(channelsinuosity(phabformat(raw)))
  hit <- '205PS0202_2013-07-17_MPSL-DFW'

  expect_true(is.na(cs[hit, 'XBEARING.result']))
  expect_true(is.na(cs[hit, 'XBEARING.sd']))

  # unaffected reaches keep their baseline values
  others <- setdiff(rownames(cs), hit)
  expect_equal(cs[others, 'XBEARING.result'], c(277.7, 307.3, 220.0))
  expect_equal(cs[others, 'XBEARING.sd'],     c(21.0, 29.1, 21.6))

  # the internal helper column must not leak into the output
  expect_false('n_bear' %in% colnames(cs))
})

test_that('XSLOPE handles gradient recorded as Slope, as Elevation Difference, or both', {

  xslope <- function(drop) {
    raw <- PHABMetrics::sampdat
    if (!is.null(drop)) raw <- raw[!(raw$AnalyteName %in% drop), ]
    suppressWarnings(channelsinuosity(phabformat(raw)))$XSLOPE.result
  }

  # sampdat records Slope for two sites and Elevation Difference for the other
  # two, so the combined case must coalesce across both sources.
  expect_equal(xslope(NULL), c(0.2, 1.2, 2.3, 0.8))

  # dropping one source must not error -- the sites that relied on it go NaN,
  # the others keep their values
  expect_equal(xslope('Slope'), c(0.2, NaN, NaN, 0.8))
  expect_equal(xslope('Elevation Difference'), c(NaN, 1.2, 2.3, NaN))

  # with neither source there is nothing to compute from
  expect_error(
    xslope(c('Slope', 'Elevation Difference')),
    'Missing Analytes'
  )
})
