# Golden-value regression tests for ripveg().
# Generated by tools/generate_golden_tests.R -- regenerate rather than hand-editing.
# Expected values are the confirmed-correct output for `sampdat` as of 2026-08-20.

test_that('ripveg() returns the expected samples in the expected order', {
  expect_equal(rownames(ripvegmet), c('105PS0231_2013-08-29_DFW-ABL', '205PS0202_2013-07-17_MPSL-DFW', '308PS0204_2013-05-21_DFW-ABL', '520PS0455_2013-07-22_MPSL-DFW'))
})

test_that('ripveg() returns the expected columns', {
  expect_equal(colnames(ripvegmet), c('XGB.result', 'XGB.count', 'XGB.sd', 'XGH.result', 'XGH.count', 'XGH.sd', 'XGW.result', 'XGW.count', 'XGW.sd', 'XM.result', 'XM.count', 'XM.sd', 'XC.result', 'XC.count', 'XC.sd', 'XG.result', 'XG.count', 'XCM.result', 'XCM.count', 'XCMG.result', 'XCMG.count', 'XPMID.result', 'XPMID.count', 'XPCAN.result', 'XPCAN.count', 'XPCM.result', 'XPCMG.result', 'XPMGVEG.result', 'XPCM.count', 'XPCMG.count', 'XPMGVEG.count', 'XPGVEG.count', 'XPGVEG.result'))
})

test_that('Checking XGB.result', {
  expect_equal(as.vector(ripvegmet$XGB.result), c(8, 38, 60, 36))
})

test_that('Checking XGB.count', {
  expect_equal(as.vector(ripvegmet$XGB.count), c(22, 22, 22, 22))
})

test_that('Checking XGB.sd', {
  expect_equal(as.vector(ripvegmet$XGB.sd), c(14.5, 26.3, 24, 27.7))
})

test_that('Checking XGH.result', {
  expect_equal(as.vector(ripvegmet$XGH.result), c(71, 8, 10, 19))
})

test_that('Checking XGH.count', {
  expect_equal(as.vector(ripvegmet$XGH.count), c(22, 22, 22, 22))
})

test_that('Checking XGH.sd', {
  expect_equal(as.vector(ripvegmet$XGH.sd), c(26.7, 16, 9.5, 18.1))
})

test_that('Checking XGW.result', {
  expect_equal(as.vector(ripvegmet$XGW.result), c(17, 43, 26, 31))
})

test_that('Checking XGW.count', {
  expect_equal(as.vector(ripvegmet$XGW.count), c(22, 22, 22, 22))
})

test_that('Checking XGW.sd', {
  expect_equal(as.vector(ripvegmet$XGW.sd), c(18.6, 30.3, 19.5, 15.1))
})

test_that('Checking XM.result', {
  expect_equal(as.vector(ripvegmet$XM.result), c(36, 34, 35, 39))
})

test_that('Checking XM.count', {
  expect_equal(as.vector(ripvegmet$XM.count), c(22, 22, 22, 22))
})

test_that('Checking XM.sd', {
  expect_equal(as.vector(ripvegmet$XM.sd), c(23.3, 16.7, 18.3, 19.3))
})

test_that('Checking XC.result', {
  expect_equal(as.vector(ripvegmet$XC.result), c(8, 57, 57, 34))
})

test_that('Checking XC.count', {
  expect_equal(as.vector(ripvegmet$XC.count), c(22, 22, 22, 22))
})

test_that('Checking XC.sd', {
  expect_equal(as.vector(ripvegmet$XC.sd), c(11, 13.6, 21.6, 22))
})

test_that('Checking XG.result', {
  expect_equal(as.vector(ripvegmet$XG.result), c(88, 51, 36, 50))
})

test_that('Checking XG.count', {
  expect_equal(as.vector(ripvegmet$XG.count), c(2, 2, 2, 2))
})

test_that('Checking XCM.result', {
  expect_equal(as.vector(ripvegmet$XCM.result), c(44, 91, 92, 73))
})

test_that('Checking XCM.count', {
  expect_equal(as.vector(ripvegmet$XCM.count), c(2, 2, 2, 2))
})

test_that('Checking XCMG.result', {
  expect_equal(as.vector(ripvegmet$XCMG.result), c(132, 142, 128, 123))
})

test_that('Checking XCMG.count', {
  expect_equal(as.vector(ripvegmet$XCMG.count), c(4, 4, 4, 4))
})

test_that('Checking XPMID.result', {
  expect_equal(as.vector(ripvegmet$XPMID.result), c(0.95, 1, 1, 1))
})

test_that('Checking XPMID.count', {
  expect_equal(as.vector(ripvegmet$XPMID.count), c(22, 22, 22, 22))
})

test_that('Checking XPCAN.result', {
  expect_equal(as.vector(ripvegmet$XPCAN.result), c(0.45, 1, 1, 0.95))
})

test_that('Checking XPCAN.count', {
  expect_equal(as.vector(ripvegmet$XPCAN.count), c(22, 22, 22, 22))
})

test_that('Checking XPCM.result', {
  expect_equal(as.vector(ripvegmet$XPCM.result), c(0.45, 1, 1, 0.95))
})

test_that('Checking XPCMG.result', {
  expect_equal(as.vector(ripvegmet$XPCMG.result), c(0.45, 1, 1, 0.95))
})

test_that('Checking XPMGVEG.result', {
  expect_equal(as.vector(ripvegmet$XPMGVEG.result), c(1, 0.91, 0.77, 0.95))
})

test_that('Checking XPCM.count', {
  expect_equal(as.vector(ripvegmet$XPCM.count), c(22, 22, 22, 22))
})

test_that('Checking XPCMG.count', {
  expect_equal(as.vector(ripvegmet$XPCMG.count), c(22, 22, 22, 22))
})

test_that('Checking XPMGVEG.count', {
  expect_equal(as.vector(ripvegmet$XPMGVEG.count), c(22, 22, 22, 22))
})

test_that('Checking XPGVEG.count', {
  expect_equal(as.vector(ripvegmet$XPGVEG.count), c(22, 22, 22, 22))
})

test_that('Checking XPGVEG.result', {
  expect_equal(as.vector(ripvegmet$XPGVEG.result), c(1, 1, 1, 1))
})

