# Golden-value regression tests for algae().
# Generated by tools/generate_golden_tests.R -- regenerate rather than hand-editing.
# Expected values are the confirmed-correct output for `sampdat` as of 2026-08-20.

test_that('algae() returns the expected samples in the expected order', {
  expect_equal(rownames(algaemet), c('105PS0231_2013-08-29_DFW-ABL', '205PS0202_2013-07-17_MPSL-DFW', '308PS0204_2013-05-21_DFW-ABL', '520PS0455_2013-07-22_MPSL-DFW'))
})

test_that('algae() returns the expected columns', {
  expect_equal(colnames(algaemet), c('XMIAT.result', 'XMIAT.count', 'XMIAT.sd', 'XMIATP.result', 'XMIATP.count', 'XMIATP.sd', 'PCT_MIATP.result', 'PCT_MIAT1.result', 'PCT_MIAT1P.result', 'PCT_MAA.result', 'PCT_MCP.result', 'PCT_MAU.result', 'PCT_MAA.count', 'PCT_MAU.count', 'PCT_MCP.count', 'PCT_MIAT1.count', 'PCT_MIAT1P.count', 'PCT_MIATP.count', 'PCT_MAP.count', 'PCT_MAP.result', 'PCT_NSA.count', 'PCT_NSA.result'))
})

test_that('Checking XMIAT.result', {
  expect_equal(as.vector(algaemet$XMIAT.result), c(0.1, 0.2, 0.2, 0))
})

test_that('Checking XMIAT.count', {
  expect_equal(as.vector(algaemet$XMIAT.count), c(101, 105, 71, 95))
})

test_that('Checking XMIAT.sd', {
  expect_equal(as.vector(algaemet$XMIAT.sd), c(0.16, 0.21, 0.15, 0.04))
})

test_that('Checking XMIATP.result', {
  expect_equal(as.vector(algaemet$XMIATP.result), c(0.3, 0.4, 0.3, 0.2))
})

test_that('Checking XMIATP.count', {
  expect_equal(as.vector(algaemet$XMIATP.count), c(26, 41, 59, 3))
})

test_that('Checking XMIATP.sd', {
  expect_equal(as.vector(algaemet$XMIATP.sd), c(0.12, 0.12, 0.1, 0))
})

test_that('Checking PCT_MIATP.result', {
  expect_equal(as.vector(algaemet$PCT_MIATP.result), c(26, 39, 83, 3))
})

test_that('Checking PCT_MIAT1.result', {
  expect_equal(as.vector(algaemet$PCT_MIAT1.result), c(0, 0, 0, 0))
})

test_that('Checking PCT_MIAT1P.result', {
  expect_equal(as.vector(algaemet$PCT_MIAT1P.result), c(0, 0, 0, 0))
})

test_that('Checking PCT_MAA.result', {
  expect_equal(as.vector(algaemet$PCT_MAA.result), c(2, 16, 9, 56))
})

test_that('Checking PCT_MCP.result', {
  expect_equal(as.vector(algaemet$PCT_MCP.result), c(82, 0, 0, 2))
})

test_that('Checking PCT_MAU.result', {
  expect_equal(as.vector(algaemet$PCT_MAU.result), c(0, 0, 0, 0))
})

test_that('Checking PCT_MAA.count', {
  expect_equal(as.vector(algaemet$PCT_MAA.count), c(105, 105, 104, 95))
})

test_that('Checking PCT_MAU.count', {
  expect_equal(as.vector(algaemet$PCT_MAU.count), c(105, 105, 104, 95))
})

test_that('Checking PCT_MCP.count', {
  expect_equal(as.vector(algaemet$PCT_MCP.count), c(105, 105, 104, 95))
})

test_that('Checking PCT_MIAT1.count', {
  expect_equal(as.vector(algaemet$PCT_MIAT1.count), c(101, 105, 71, 95))
})

test_that('Checking PCT_MIAT1P.count', {
  expect_equal(as.vector(algaemet$PCT_MIAT1P.count), c(26, 41, 59, 3))
})

test_that('Checking PCT_MIATP.count', {
  expect_equal(as.vector(algaemet$PCT_MIATP.count), c(101, 105, 71, 95))
})

test_that('Checking PCT_MAP.count', {
  expect_equal(as.vector(algaemet$PCT_MAP.count), c(105, 105, 104, 95))
})

test_that('Checking PCT_MAP.result', {
  expect_equal(as.vector(algaemet$PCT_MAP.result), c(2, 16, 9, 56))
})

test_that('Checking PCT_NSA.count', {
  expect_equal(as.vector(algaemet$PCT_NSA.count), c(105, 105, 104, 95))
})

test_that('Checking PCT_NSA.result', {
  expect_equal(as.vector(algaemet$PCT_NSA.result), c(2, 16, 9, 56))
})

