# Golden-value regression tests for channelsinuosity().
# Generated by tools/generate_golden_tests.R -- regenerate rather than hand-editing.
# Expected values are the confirmed-correct output for `sampdat` as of 2026-08-20.

test_that('channelsinuosity() returns the expected samples in the expected order', {
  expect_equal(rownames(channelsinuositymet), c('105PS0231_2013-08-29_DFW-ABL', '205PS0202_2013-07-17_MPSL-DFW', '308PS0204_2013-05-21_DFW-ABL', '520PS0455_2013-07-22_MPSL-DFW'))
})

test_that('channelsinuosity() returns the expected columns', {
  expect_equal(colnames(channelsinuositymet), c('XSLOPE.count', 'XSLOPE.result', 'XSLOPE.sd', 'SLOPE_0.count', 'SLOPE_0_5.count', 'SLOPE_1.count', 'SLOPE_2.count', 'SLOPE_0.result', 'SLOPE_0_5.result', 'SLOPE_1.result', 'SLOPE_2.result', 'XBEARING.count', 'XBEARING.result', 'XBEARING.sd', 'SINU.result', 'SINU.count'))
})

test_that('Checking XSLOPE.count', {
  expect_equal(as.vector(channelsinuositymet$XSLOPE.count), c(10, 10, 10, 10))
})

test_that('Checking XSLOPE.result', {
  expect_equal(as.vector(channelsinuositymet$XSLOPE.result), c(0.2, 1.2, 2.3, 0.8))
})

test_that('Checking XSLOPE.sd', {
  expect_equal(as.vector(channelsinuositymet$XSLOPE.sd), c(0.12, 0.59, 1.49, 0.89))
})

test_that('Checking SLOPE_0.count', {
  expect_equal(as.vector(channelsinuositymet$SLOPE_0.count), c(10, 10, 10, 10))
})

test_that('Checking SLOPE_0_5.count', {
  expect_equal(as.vector(channelsinuositymet$SLOPE_0_5.count), c(10, 10, 10, 10))
})

test_that('Checking SLOPE_1.count', {
  expect_equal(as.vector(channelsinuositymet$SLOPE_1.count), c(10, 10, 10, 10))
})

test_that('Checking SLOPE_2.count', {
  expect_equal(as.vector(channelsinuositymet$SLOPE_2.count), c(10, 10, 10, 10))
})

test_that('Checking SLOPE_0.result', {
  expect_equal(as.vector(channelsinuositymet$SLOPE_0.result), c(0, 0, 0, 0))
})

test_that('Checking SLOPE_0_5.result', {
  expect_equal(as.vector(channelsinuositymet$SLOPE_0_5.result), c(100, 20, 0, 60))
})

test_that('Checking SLOPE_1.result', {
  expect_equal(as.vector(channelsinuositymet$SLOPE_1.result), c(100, 60, 40, 70))
})

test_that('Checking SLOPE_2.result', {
  expect_equal(as.vector(channelsinuositymet$SLOPE_2.result), c(100, 90, 70, 90))
})

test_that('Checking XBEARING.count', {
  expect_equal(as.vector(channelsinuositymet$XBEARING.count), c(10, 10, 10, 10))
})

test_that('Checking XBEARING.result', {
  expect_equal(as.vector(channelsinuositymet$XBEARING.result), c(277.7, 72.5, 307.3, 220))
})

test_that('Checking XBEARING.sd', {
  expect_equal(as.vector(channelsinuositymet$XBEARING.sd), c(21, 100.4, 29.1, 21.6))
})

test_that('Checking SINU.result', {
  expect_equal(as.vector(channelsinuositymet$SINU.result), c(1.06, 1.06, 1.13, 1.07))
})

test_that('Checking SINU.count', {
  expect_equal(as.vector(channelsinuositymet$SINU.count), c(10, 10, 10, 10))
})

