# Golden-value regression tests for misc().
# Generated by tools/generate_golden_tests.R -- regenerate rather than hand-editing.
# Expected values are the confirmed-correct output for `sampdat` as of 2026-08-20.

test_that('misc() returns the expected samples in the expected order', {
  expect_equal(rownames(miscmet), c('308PS0204_2013-05-21_DFW-ABL', '205PS0202_2013-07-17_MPSL-DFW', '520PS0455_2013-07-22_MPSL-DFW', '105PS0231_2013-08-29_DFW-ABL'))
})

test_that('misc() returns the expected columns', {
  expect_equal(colnames(miscmet), c('NFC_DLU.result', 'NFC_EFR.result', 'NFC_ERN.result', 'RBP_CHN.result', 'RBP_EPI.result', 'RBP_SED.result'))
})

test_that('Checking NFC_DLU.result', {
  expect_equal(as.vector(miscmet$NFC_DLU.result), c('FOREST', 'SUBURBAN, TOWN', 'URBAN/INDUSTRIAL', 'RANGE'))
})

test_that('Checking NFC_EFR.result', {
  expect_equal(as.vector(miscmet$NFC_EFR.result), c('NO', 'NO', 'NO', 'NO'))
})

test_that('Checking NFC_ERN.result', {
  expect_equal(as.vector(miscmet$NFC_ERN.result), c('NO', 'NO', 'NO', 'NO'))
})

test_that('Checking RBP_CHN.result', {
  expect_equal(as.vector(miscmet$RBP_CHN.result), c('19', '13', '16', NA_character_))
})

test_that('Checking RBP_EPI.result', {
  expect_equal(as.vector(miscmet$RBP_EPI.result), c('20', '12', '18', NA_character_))
})

test_that('Checking RBP_SED.result', {
  expect_equal(as.vector(miscmet$RBP_SED.result), c('20', '13', '13', NA_character_))
})

