# Golden-value regression tests for channelmorph().
# Generated by tools/generate_golden_tests.R -- regenerate rather than hand-editing.
# Expected values are the confirmed-correct output for `sampdat` as of 2026-08-20.

test_that('channelmorph() returns the expected samples in the expected order', {
  expect_equal(rownames(channelmorphmet), c('105PS0231_2013-08-29_DFW-ABL', '205PS0202_2013-07-17_MPSL-DFW', '308PS0204_2013-05-21_DFW-ABL', '520PS0455_2013-07-22_MPSL-DFW'))
})

test_that('channelmorph() returns the expected columns', {
  expect_equal(colnames(channelmorphmet), c('PCT_CF.result', 'PCT_CF.count', 'PCT_CF.sd', 'PCT_DR.result', 'PCT_DR.count', 'PCT_DR.sd', 'PCT_GL.result', 'PCT_GL.count', 'PCT_GL.sd', 'PCT_POOL.result', 'PCT_POOL.count', 'PCT_POOL.sd', 'PCT_RA.result', 'PCT_RA.count', 'PCT_RA.sd', 'PCT_RI.result', 'PCT_RI.count', 'PCT_RI.sd', 'PCT_RN.result', 'PCT_RN.count', 'PCT_RN.sd', 'PCT_FAST.result', 'PCT_SLOW.result', 'PCT_CF_WT.result', 'PCT_CF_WT.count', 'PCT_GL_WT.result', 'PCT_GL_WT.count', 'PCT_POOL_WT.result', 'PCT_POOL_WT.count', 'PCT_RA_WT.result', 'PCT_RA_WT.count', 'PCT_RI_WT.result', 'PCT_RI_WT.count', 'PCT_RN_WT.result', 'PCT_RN_WT.count', 'PCT_FAST_WT.result', 'PCT_SLOW_WT.result', 'PCT_FAST.count', 'PCT_SLOW.count', 'PCT_FAST_WT.count', 'PCT_SLOW_WT.count', 'Rich_FlowHab.result', 'Rich_FlowHab.count', 'Rich_FlowHab4.result', 'Rich_FlowHab4.count', 'H_FlowHab.result', 'H_FlowHab.count', 'Ev_FlowHab.result', 'Ev_FlowHab.count', 'H_FlowHab_mod1.result'))
})

test_that('Checking PCT_CF.result', {
  expect_equal(as.vector(channelmorphmet$PCT_CF.result), c(0, 0, 0, 1))
})

test_that('Checking PCT_CF.count', {
  expect_equal(as.vector(channelmorphmet$PCT_CF.count), c(10, 10, 10, 10))
})

test_that('Checking PCT_CF.sd', {
  expect_equal(as.vector(channelmorphmet$PCT_CF.sd), c(0, 0, 0, 3.2))
})

test_that('Checking PCT_DR.result', {
  expect_equal(as.vector(channelmorphmet$PCT_DR.result), c(0, 0, 0, 0))
})

test_that('Checking PCT_DR.count', {
  expect_equal(as.vector(channelmorphmet$PCT_DR.count), c(10, 10, 10, 10))
})

test_that('Checking PCT_DR.sd', {
  expect_equal(as.vector(channelmorphmet$PCT_DR.sd), c(0, 0, 0, 0))
})

test_that('Checking PCT_GL.result', {
  expect_equal(as.vector(channelmorphmet$PCT_GL.result), c(0, 71, 3, 48))
})

test_that('Checking PCT_GL.count', {
  expect_equal(as.vector(channelmorphmet$PCT_GL.count), c(10, 10, 10, 10))
})

test_that('Checking PCT_GL.sd', {
  expect_equal(as.vector(channelmorphmet$PCT_GL.sd), c(0, 19.8, 4.8, 25.2))
})

test_that('Checking PCT_POOL.result', {
  expect_equal(as.vector(channelmorphmet$PCT_POOL.result), c(0, 0, 1, 14))
})

test_that('Checking PCT_POOL.count', {
  expect_equal(as.vector(channelmorphmet$PCT_POOL.count), c(10, 10, 10, 10))
})

test_that('Checking PCT_POOL.sd', {
  expect_equal(as.vector(channelmorphmet$PCT_POOL.sd), c(0, 0, 3.2, 23.1))
})

test_that('Checking PCT_RA.result', {
  expect_equal(as.vector(channelmorphmet$PCT_RA.result), c(0, 0, 0, 0))
})

test_that('Checking PCT_RA.count', {
  expect_equal(as.vector(channelmorphmet$PCT_RA.count), c(10, 10, 10, 10))
})

test_that('Checking PCT_RA.sd', {
  expect_equal(as.vector(channelmorphmet$PCT_RA.sd), c(0, 0, 0, 0))
})

test_that('Checking PCT_RI.result', {
  expect_equal(as.vector(channelmorphmet$PCT_RI.result), c(0, 29, 94, 22))
})

test_that('Checking PCT_RI.count', {
  expect_equal(as.vector(channelmorphmet$PCT_RI.count), c(10, 10, 10, 10))
})

test_that('Checking PCT_RI.sd', {
  expect_equal(as.vector(channelmorphmet$PCT_RI.sd), c(0, 19.8, 8.4, 31.6))
})

test_that('Checking PCT_RN.result', {
  expect_equal(as.vector(channelmorphmet$PCT_RN.result), c(100, 0, 2, 14))
})

test_that('Checking PCT_RN.count', {
  expect_equal(as.vector(channelmorphmet$PCT_RN.count), c(10, 10, 10, 10))
})

test_that('Checking PCT_RN.sd', {
  expect_equal(as.vector(channelmorphmet$PCT_RN.sd), c(0, 0, 4.2, 19.6))
})

test_that('Checking PCT_FAST.result', {
  expect_equal(as.vector(channelmorphmet$PCT_FAST.result), c(100, 29, 96, 37))
})

test_that('Checking PCT_SLOW.result', {
  expect_equal(as.vector(channelmorphmet$PCT_SLOW.result), c(0, 71, 4, 62))
})

test_that('Checking PCT_CF_WT.result', {
  expect_equal(as.vector(channelmorphmet$PCT_CF_WT.result), c(0, 0, 0, 1))
})

test_that('Checking PCT_CF_WT.count', {
  expect_equal(as.vector(channelmorphmet$PCT_CF_WT.count), c(10, 10, 10, 10))
})

test_that('Checking PCT_GL_WT.result', {
  expect_equal(as.vector(channelmorphmet$PCT_GL_WT.result), c(0, 71, 3, 48))
})

test_that('Checking PCT_GL_WT.count', {
  expect_equal(as.vector(channelmorphmet$PCT_GL_WT.count), c(10, 10, 10, 10))
})

test_that('Checking PCT_POOL_WT.result', {
  expect_equal(as.vector(channelmorphmet$PCT_POOL_WT.result), c(0, 0, 1, 14))
})

test_that('Checking PCT_POOL_WT.count', {
  expect_equal(as.vector(channelmorphmet$PCT_POOL_WT.count), c(10, 10, 10, 10))
})

test_that('Checking PCT_RA_WT.result', {
  expect_equal(as.vector(channelmorphmet$PCT_RA_WT.result), c(0, 0, 0, 0))
})

test_that('Checking PCT_RA_WT.count', {
  expect_equal(as.vector(channelmorphmet$PCT_RA_WT.count), c(10, 10, 10, 10))
})

test_that('Checking PCT_RI_WT.result', {
  expect_equal(as.vector(channelmorphmet$PCT_RI_WT.result), c(0, 29, 94, 22))
})

test_that('Checking PCT_RI_WT.count', {
  expect_equal(as.vector(channelmorphmet$PCT_RI_WT.count), c(10, 10, 10, 10))
})

test_that('Checking PCT_RN_WT.result', {
  expect_equal(as.vector(channelmorphmet$PCT_RN_WT.result), c(100, 0, 2, 14))
})

test_that('Checking PCT_RN_WT.count', {
  expect_equal(as.vector(channelmorphmet$PCT_RN_WT.count), c(10, 10, 10, 10))
})

test_that('Checking PCT_FAST_WT.result', {
  expect_equal(as.vector(channelmorphmet$PCT_FAST_WT.result), c(100, 29, 96, 37))
})

test_that('Checking PCT_SLOW_WT.result', {
  expect_equal(as.vector(channelmorphmet$PCT_SLOW_WT.result), c(0, 71, 4, 62))
})

test_that('Checking PCT_FAST.count', {
  expect_equal(as.vector(channelmorphmet$PCT_FAST.count), c(4, 4, 4, 4))
})

test_that('Checking PCT_SLOW.count', {
  expect_equal(as.vector(channelmorphmet$PCT_SLOW.count), c(2, 2, 2, 2))
})

test_that('Checking PCT_FAST_WT.count', {
  expect_equal(as.vector(channelmorphmet$PCT_FAST_WT.count), c(4, 4, 4, 4))
})

test_that('Checking PCT_SLOW_WT.count', {
  expect_equal(as.vector(channelmorphmet$PCT_SLOW_WT.count), c(2, 2, 2, 2))
})

test_that('Checking Rich_FlowHab.result', {
  expect_equal(as.vector(channelmorphmet$Rich_FlowHab.result), c(1, 2, 4, 5))
})

test_that('Checking Rich_FlowHab.count', {
  expect_equal(as.vector(channelmorphmet$Rich_FlowHab.count), c(10, 10, 10, 10))
})

test_that('Checking Rich_FlowHab4.result', {
  expect_equal(as.vector(channelmorphmet$Rich_FlowHab4.result), c(1, 2, 4, 4))
})

test_that('Checking Rich_FlowHab4.count', {
  expect_equal(as.vector(channelmorphmet$Rich_FlowHab4.count), c(10, 10, 10, 10))
})

test_that('Checking H_FlowHab.result', {
  expect_equal(as.vector(channelmorphmet$H_FlowHab.result), c(0, 0.6, 0.29, 1.29))
})

test_that('Checking H_FlowHab.count', {
  expect_equal(as.vector(channelmorphmet$H_FlowHab.count), c(1, 2, 4, 5))
})

test_that('Checking Ev_FlowHab.result', {
  expect_equal(as.vector(channelmorphmet$Ev_FlowHab.result), c(0, 0.87, 0.21, 0.8))
})

test_that('Checking Ev_FlowHab.count', {
  expect_equal(as.vector(channelmorphmet$Ev_FlowHab.count), c(1, 2, 4, 5))
})

test_that('Checking H_FlowHab_mod1.result', {
  expect_equal(as.vector(channelmorphmet$H_FlowHab_mod1.result), c(0, 0.51, 0.19, 0.72))
})

