# Golden-value regression tests for disturbance().
# Generated by tools/generate_golden_tests.R -- regenerate rather than hand-editing.
# Expected values are the confirmed-correct output for `sampdat` as of 2026-08-20.

test_that('disturbance() returns the expected samples in the expected order', {
  expect_equal(rownames(disturbancemet), c('308PS0204_2013-05-21_DFW-ABL', '205PS0202_2013-07-17_MPSL-DFW', '520PS0455_2013-07-22_MPSL-DFW', '105PS0231_2013-08-29_DFW-ABL'))
})

test_that('disturbance() returns the expected columns', {
  expect_equal(colnames(disturbancemet), c('W1H_BRDG.result', 'W1H_BRDG.count', 'W1H_BRDG.sd', 'W1H_BLDG.result', 'W1H_BLDG.count', 'W1H_BLDG.sd', 'W1H_LDFL.result', 'W1H_LDFL.count', 'W1H_LDFL.sd', 'W1H_LOG.result', 'W1H_LOG.count', 'W1H_LOG.sd', 'W1H_MINE.result', 'W1H_MINE.count', 'W1H_MINE.sd', 'W1H_ORVY.result', 'W1H_ORVY.count', 'W1H_ORVY.sd', 'W1H_PARK.result', 'W1H_PARK.count', 'W1H_PARK.sd', 'W1H_PSTR.result', 'W1H_PSTR.count', 'W1H_PSTR.sd', 'W1H_PVMT.result', 'W1H_PVMT.count', 'W1H_PVMT.sd', 'W1H_PIPE.result', 'W1H_PIPE.count', 'W1H_PIPE.sd', 'W1H_ROAD.result', 'W1H_ROAD.count', 'W1H_ROAD.sd', 'W1H_CROP.result', 'W1H_CROP.count', 'W1H_CROP.sd', 'W1H_VEGM.result', 'W1H_VEGM.count', 'W1H_VEGM.sd', 'W1H_WALL.result', 'W1H_WALL.count', 'W1H_WALL.sd', 'W1_HALL_EMAP.result', 'W1_HALL_EMAP.count', 'W1_HALL_SWAMP.result', 'W1_HALL_SWAMP.count'))
})

test_that('Checking W1H_BRDG.result', {
  expect_equal(as.vector(disturbancemet$W1H_BRDG.result), c(0, 0, 0, 0))
})

test_that('Checking W1H_BRDG.count', {
  expect_equal(as.vector(disturbancemet$W1H_BRDG.count), c(22, 22, 22, 22))
})

test_that('Checking W1H_BRDG.sd', {
  expect_equal(as.vector(disturbancemet$W1H_BRDG.sd), c(0, 0, 0, 0))
})

test_that('Checking W1H_BLDG.result', {
  expect_equal(as.vector(disturbancemet$W1H_BLDG.result), c(0, 0.73, 0.18, 0))
})

test_that('Checking W1H_BLDG.count', {
  expect_equal(as.vector(disturbancemet$W1H_BLDG.count), c(22, 22, 22, 22))
})

test_that('Checking W1H_BLDG.sd', {
  expect_equal(as.vector(disturbancemet$W1H_BLDG.sd), c(0, 0.131, 0.304, 0))
})

test_that('Checking W1H_LDFL.result', {
  expect_equal(as.vector(disturbancemet$W1H_LDFL.result), c(0.25, 0.48, 0.14, 0))
})

test_that('Checking W1H_LDFL.count', {
  expect_equal(as.vector(disturbancemet$W1H_LDFL.count), c(22, 22, 22, 22))
})

test_that('Checking W1H_LDFL.sd', {
  expect_equal(as.vector(disturbancemet$W1H_LDFL.sd), c(0.551, 0.715, 0.441, 0))
})

test_that('Checking W1H_LOG.result', {
  expect_equal(as.vector(disturbancemet$W1H_LOG.result), c(0, 0, 0, 0))
})

test_that('Checking W1H_LOG.count', {
  expect_equal(as.vector(disturbancemet$W1H_LOG.count), c(22, 22, 22, 22))
})

test_that('Checking W1H_LOG.sd', {
  expect_equal(as.vector(disturbancemet$W1H_LOG.sd), c(0, 0, 0, 0))
})

test_that('Checking W1H_MINE.result', {
  expect_equal(as.vector(disturbancemet$W1H_MINE.result), c(0, 0, 0, 0))
})

test_that('Checking W1H_MINE.count', {
  expect_equal(as.vector(disturbancemet$W1H_MINE.count), c(22, 22, 22, 22))
})

test_that('Checking W1H_MINE.sd', {
  expect_equal(as.vector(disturbancemet$W1H_MINE.sd), c(0, 0, 0, 0))
})

test_that('Checking W1H_ORVY.result', {
  expect_equal(as.vector(disturbancemet$W1H_ORVY.result), c(0, 0, 0, 0))
})

test_that('Checking W1H_ORVY.count', {
  expect_equal(as.vector(disturbancemet$W1H_ORVY.count), c(22, 22, 22, 22))
})

test_that('Checking W1H_ORVY.sd', {
  expect_equal(as.vector(disturbancemet$W1H_ORVY.sd), c(0, 0, 0, 0))
})

test_that('Checking W1H_PARK.result', {
  expect_equal(as.vector(disturbancemet$W1H_PARK.result), c(0, 0.11, 0, 0))
})

test_that('Checking W1H_PARK.count', {
  expect_equal(as.vector(disturbancemet$W1H_PARK.count), c(22, 22, 22, 22))
})

test_that('Checking W1H_PARK.sd', {
  expect_equal(as.vector(disturbancemet$W1H_PARK.sd), c(0, 0.376, 0, 0))
})

test_that('Checking W1H_PSTR.result', {
  expect_equal(as.vector(disturbancemet$W1H_PSTR.result), c(0, 0, 0, 0))
})

test_that('Checking W1H_PSTR.count', {
  expect_equal(as.vector(disturbancemet$W1H_PSTR.count), c(22, 22, 22, 22))
})

test_that('Checking W1H_PSTR.sd', {
  expect_equal(as.vector(disturbancemet$W1H_PSTR.sd), c(0, 0, 0, 0))
})

test_that('Checking W1H_PVMT.result', {
  expect_equal(as.vector(disturbancemet$W1H_PVMT.result), c(0.03, 0, 0.27, 0))
})

test_that('Checking W1H_PVMT.count', {
  expect_equal(as.vector(disturbancemet$W1H_PVMT.count), c(22, 22, 22, 22))
})

test_that('Checking W1H_PVMT.sd', {
  expect_equal(as.vector(disturbancemet$W1H_PVMT.sd), c(0.142, 0, 0.336, 0))
})

test_that('Checking W1H_PIPE.result', {
  expect_equal(as.vector(disturbancemet$W1H_PIPE.result), c(0, 0, 0, 0))
})

test_that('Checking W1H_PIPE.count', {
  expect_equal(as.vector(disturbancemet$W1H_PIPE.count), c(22, 22, 22, 22))
})

test_that('Checking W1H_PIPE.sd', {
  expect_equal(as.vector(disturbancemet$W1H_PIPE.sd), c(0, 0, 0, 0))
})

test_that('Checking W1H_ROAD.result', {
  expect_equal(as.vector(disturbancemet$W1H_ROAD.result), c(0.24, 0, 0.05, 0))
})

test_that('Checking W1H_ROAD.count', {
  expect_equal(as.vector(disturbancemet$W1H_ROAD.count), c(22, 22, 22, 22))
})

test_that('Checking W1H_ROAD.sd', {
  expect_equal(as.vector(disturbancemet$W1H_ROAD.sd), c(0.328, 0, 0.213, 0))
})

test_that('Checking W1H_CROP.result', {
  expect_equal(as.vector(disturbancemet$W1H_CROP.result), c(0, 0, 0, 0))
})

test_that('Checking W1H_CROP.count', {
  expect_equal(as.vector(disturbancemet$W1H_CROP.count), c(22, 22, 22, 22))
})

test_that('Checking W1H_CROP.sd', {
  expect_equal(as.vector(disturbancemet$W1H_CROP.sd), c(0, 0, 0, 0))
})

test_that('Checking W1H_VEGM.result', {
  expect_equal(as.vector(disturbancemet$W1H_VEGM.result), c(0, 0, 0, 0))
})

test_that('Checking W1H_VEGM.count', {
  expect_equal(as.vector(disturbancemet$W1H_VEGM.count), c(22, 22, 22, 22))
})

test_that('Checking W1H_VEGM.sd', {
  expect_equal(as.vector(disturbancemet$W1H_VEGM.sd), c(0, 0, 0, 0))
})

test_that('Checking W1H_WALL.result', {
  expect_equal(as.vector(disturbancemet$W1H_WALL.result), c(0.14, 0.55, 0.64, 0))
})

test_that('Checking W1H_WALL.count', {
  expect_equal(as.vector(disturbancemet$W1H_WALL.count), c(22, 22, 22, 22))
})

test_that('Checking W1H_WALL.sd', {
  expect_equal(as.vector(disturbancemet$W1H_WALL.sd), c(0.441, 0.575, 0.727, 0))
})

test_that('Checking W1_HALL_EMAP.result', {
  expect_equal(as.vector(disturbancemet$W1_HALL_EMAP.result), c(0.66, 1.87, 1.28, 0))
})

test_that('Checking W1_HALL_EMAP.count', {
  expect_equal(as.vector(disturbancemet$W1_HALL_EMAP.count), c(11, 11, 11, 11))
})

test_that('Checking W1_HALL_SWAMP.result', {
  expect_equal(as.vector(disturbancemet$W1_HALL_SWAMP.result), c(0.66, 1.87, 1.28, 0))
})

test_that('Checking W1_HALL_SWAMP.count', {
  expect_equal(as.vector(disturbancemet$W1_HALL_SWAMP.count), c(14, 14, 14, 14))
})

