# Guards the canonical metric schema in R/metric_schema.R, which phabmetrics()
# uses to backfill missing metrics (NA result, 0 count) instead of dropping them.
#
# Hand-maintained; NOT generated by tools/generate_golden_tests.R.

test_that('metric_schema matches what each subfunction actually returns', {

  # If this fails you added or renamed a metric. Regenerate the schema rather
  # than editing it by hand, otherwise the new metric will be silently absent
  # from phabmetrics() output whenever its subfunction fails.
  actual <- list(
    bankmorph        = colnames(bankmorphmet),
    channelmorph     = colnames(channelmorphmet),
    channelsinuosity = colnames(channelsinuositymet),
    densiometer      = colnames(densiometermet),
    habitat          = colnames(habitatmet),
    disturbance      = colnames(disturbancemet),
    flow             = colnames(flowmet),
    misc             = colnames(miscmet),
    bankstability    = colnames(bankstabilitymet),
    quality          = colnames(qualitymet),
    ripveg           = colnames(ripvegmet),
    substrate        = colnames(submet),
    algae            = colnames(algaemet)
  )

  expect_equal(sort(names(PHABMetrics:::metric_schema)), sort(names(actual)))

  for (fn in names(actual)) {
    expect_equal(PHABMetrics:::metric_schema[[fn]], actual[[fn]], info = fn)
  }
})

test_that('phabmetrics() returns a full grid when a subfunction fails', {

  raw <- PHABMetrics::sampdat
  full <- suppressWarnings(phabmetrics(raw))

  # algae crashes when Microalgae Thickness is absent but other algae analytes
  # are present -- cbind() of a zero-row and a four-row frame.
  broken <- raw[!(raw$AnalyteName %in% 'Microalgae Thickness'), ]
  p <- suppressWarnings(phabmetrics(broken))

  expect_equal(nrow(p), nrow(full))
  expect_equal(sort(unique(p$Variable)), sort(unique(full$Variable)))
  expect_equal(sort(unique(p$StationCode)), sort(unique(full$StationCode)))

  algae_vars <- c('XMIAT','XMIATP','PCT_MIATP','PCT_MIAT1','PCT_MIAT1P',
                  'PCT_MAA','PCT_MAU','PCT_MAP','PCT_MCP','PCT_NSA')
  alg <- p[p$Variable %in% algae_vars, ]
  expect_equal(nrow(alg), length(algae_vars) * 4)
  expect_true(all(is.na(alg$Result)))
  expect_true(all(alg$Count_Calc == 0))

  # every other metric is untouched
  keep <- !(full$Variable %in% algae_vars)
  expect_equal(p[keep, 'Result'], full[keep, 'Result'])
})

test_that('phabmetrics() fills columns a subfunction omits without failing', {

  # Dropping Macrophyte Cover does not error -- algae returns 20 of its 22
  # columns, so PCT_MCP/PCT_MAP used to vanish with no warning at all.
  raw <- PHABMetrics::sampdat
  short <- raw[!(raw$AnalyteName %in% 'Macrophyte Cover'), ]
  p <- suppressWarnings(phabmetrics(short))

  expect_equal(nrow(p), nrow(suppressWarnings(phabmetrics(raw))))

  # only PCT_MCP is lost -- it is the one metric read straight off that analyte
  gone <- p[p$Variable == 'PCT_MCP', ]
  expect_equal(nrow(gone), 4)
  expect_true(all(is.na(gone$Result)))
  expect_true(all(gone$Count_Calc == 0))

  # metrics algae still computed keep real values and must not be blanked --
  # PCT_MAP is derived from other analytes and survives
  expect_false(any(is.na(p$Result[p$Variable == 'XMIAT'])))
  expect_false(any(is.na(p$Result[p$Variable == 'PCT_MAP'])))
  expect_true(all(p$Count_Calc[p$Variable == 'PCT_MAP'] > 0))
})

test_that('phabmetrics() warns when a subfunction failed', {

  broken <- PHABMetrics::sampdat[
    !(PHABMetrics::sampdat$AnalyteName %in% 'Microalgae Thickness'), ]

  w <- character()
  withCallingHandlers(
    phabmetrics(broken),
    warning = function(x) { w <<- c(w, conditionMessage(x)); invokeRestart('muffleWarning') }
  )
  expect_true(any(grepl('algae', grep('^phabmetrics:', w, value = TRUE))))

  # complete data warns nothing
  w2 <- character()
  withCallingHandlers(
    phabmetrics(PHABMetrics::sampdat),
    warning = function(x) { w2 <<- c(w2, conditionMessage(x)); invokeRestart('muffleWarning') }
  )
  expect_length(grep('^phabmetrics:', w2, value = TRUE), 0)
})
