# Golden-value regression tests for habitat().
# Generated by tools/generate_golden_tests.R -- regenerate rather than hand-editing.
# Expected values are the confirmed-correct output for `sampdat` as of 2026-08-20.

test_that('habitat() returns the expected samples in the expected order', {
  expect_equal(rownames(habitatmet), c('105PS0231_2013-08-29_DFW-ABL', '205PS0202_2013-07-17_MPSL-DFW', '308PS0204_2013-05-21_DFW-ABL', '520PS0455_2013-07-22_MPSL-DFW'))
})

test_that('habitat() returns the expected columns', {
  expect_equal(colnames(habitatmet), c('XFC_AQM.result', 'XFC_AQM.count', 'XFC_AQM.sd', 'XFC_HUM.result', 'XFC_HUM.count', 'XFC_HUM.sd', 'XFC_RCK.result', 'XFC_RCK.count', 'XFC_RCK.sd', 'XFC_ALG.result', 'XFC_ALG.count', 'XFC_ALG.sd', 'XFC_LWD.result', 'XFC_LWD.count', 'XFC_LWD.sd', 'XFC_LTR.result', 'XFC_LTR.count', 'XFC_LTR.sd', 'XFC_OHV.result', 'XFC_OHV.count', 'XFC_OHV.sd', 'XFC_BRS.result', 'XFC_BRS.count', 'XFC_BRS.sd', 'XFC_UCB.result', 'XFC_UCB.count', 'XFC_UCB.sd', 'XFC_BIG.result', 'XFC_NAT_EMAP.result', 'XFC_NAT_SWAMP.result', 'CFC_AQM.result', 'CFC_HUM.result', 'CFC_RCK.result', 'CFC_ALG.result', 'CFC_LWD.result', 'CFC_LTR.result', 'CFC_OHV.result', 'CFC_BRS.result', 'CFC_UCB.result', 'CFC_ALL_EMAP.result', 'CFC_ALL_SWAMP.result', 'XFC_BIG.count', 'XFC_BIG3.result', 'XFC_BIG3.count', 'XFC_NAT_EMAP.count', 'XFC_NAT_SWAMP.count', 'CFC_ALL_EMAP.count', 'CFC_ALL_SWAMP.count', 'H_AqHab.result', 'H_AqHab_mod1.result', 'H_AqHab.count', 'Ev_AqHab.result', 'Ev_AqHab.count', 'CFC_ALG.count', 'CFC_AQM.count', 'CFC_BRS.count', 'CFC_HUM.count', 'CFC_LTR.count', 'CFC_LWD.count', 'CFC_OHV.count', 'CFC_RCK.count', 'CFC_UCB.count', 'Rich_AqHab.result', 'Rich_AqHab.count'))
})

test_that('Checking XFC_AQM.result', {
  expect_equal(as.vector(habitatmet$XFC_AQM.result), c(51.6, 4.5, 0.9, 4.5))
})

test_that('Checking XFC_AQM.count', {
  expect_equal(as.vector(habitatmet$XFC_AQM.count), c(11, 11, 11, 11))
})

test_that('Checking XFC_AQM.sd', {
  expect_equal(as.vector(habitatmet$XFC_AQM.sd), c(13.1, 1.5, 2, 1.5))
})

test_that('Checking XFC_HUM.result', {
  expect_equal(as.vector(habitatmet$XFC_HUM.result), c(0, 5.9, 0, 5))
})

test_that('Checking XFC_HUM.count', {
  expect_equal(as.vector(habitatmet$XFC_HUM.count), c(11, 11, 11, 11))
})

test_that('Checking XFC_HUM.sd', {
  expect_equal(as.vector(habitatmet$XFC_HUM.sd), c(0, 9.7, 0, 0))
})

test_that('Checking XFC_RCK.result', {
  expect_equal(as.vector(habitatmet$XFC_RCK.result), c(0, 12.3, 15.9, 45.7))
})

test_that('Checking XFC_RCK.count', {
  expect_equal(as.vector(habitatmet$XFC_RCK.count), c(11, 11, 11, 11))
})

test_that('Checking XFC_RCK.sd', {
  expect_equal(as.vector(habitatmet$XFC_RCK.sd), c(0, 10.1, 10.4, 16.4))
})

test_that('Checking XFC_ALG.result', {
  expect_equal(as.vector(habitatmet$XFC_ALG.result), c(0.9, 1.4, 1.8, 27.3))
})

test_that('Checking XFC_ALG.count', {
  expect_equal(as.vector(habitatmet$XFC_ALG.count), c(11, 11, 11, 11))
})

test_that('Checking XFC_ALG.sd', {
  expect_equal(as.vector(habitatmet$XFC_ALG.sd), c(2, 2.3, 2.5, 16.9))
})

test_that('Checking XFC_LWD.result', {
  expect_equal(as.vector(habitatmet$XFC_LWD.result), c(0, 0, 1.4, 4.5))
})

test_that('Checking XFC_LWD.count', {
  expect_equal(as.vector(habitatmet$XFC_LWD.count), c(11, 11, 11, 11))
})

test_that('Checking XFC_LWD.sd', {
  expect_equal(as.vector(habitatmet$XFC_LWD.sd), c(0, 0, 2.3, 1.5))
})

test_that('Checking XFC_LTR.result', {
  expect_equal(as.vector(habitatmet$XFC_LTR.result), c(4.1, 6.8, 2.7, 4.1))
})

test_that('Checking XFC_LTR.count', {
  expect_equal(as.vector(habitatmet$XFC_LTR.count), c(11, 11, 11, 11))
})

test_that('Checking XFC_LTR.sd', {
  expect_equal(as.vector(habitatmet$XFC_LTR.sd), c(2, 6, 2.6, 2))
})

test_that('Checking XFC_OHV.result', {
  expect_equal(as.vector(habitatmet$XFC_OHV.result), c(8.6, 6.4, 5, 5))
})

test_that('Checking XFC_OHV.count', {
  expect_equal(as.vector(habitatmet$XFC_OHV.count), c(11, 11, 11, 11))
})

test_that('Checking XFC_OHV.sd', {
  expect_equal(as.vector(habitatmet$XFC_OHV.sd), c(8.1, 6.4, 7.1, 0))
})

test_that('Checking XFC_BRS.result', {
  expect_equal(as.vector(habitatmet$XFC_BRS.result), c(1.8, 4.5, 4.5, 8.6))
})

test_that('Checking XFC_BRS.count', {
  expect_equal(as.vector(habitatmet$XFC_BRS.count), c(11, 11, 11, 11))
})

test_that('Checking XFC_BRS.sd', {
  expect_equal(as.vector(habitatmet$XFC_BRS.sd), c(2.5, 1.5, 1.5, 8.1))
})

test_that('Checking XFC_UCB.result', {
  expect_equal(as.vector(habitatmet$XFC_UCB.result), c(1.8, 17.7, 1.4, 4.5))
})

test_that('Checking XFC_UCB.count', {
  expect_equal(as.vector(habitatmet$XFC_UCB.count), c(11, 11, 11, 11))
})

test_that('Checking XFC_UCB.sd', {
  expect_equal(as.vector(habitatmet$XFC_UCB.sd), c(2.5, 10.1, 2.3, 1.5))
})

test_that('Checking XFC_BIG.result', {
  expect_equal(as.vector(habitatmet$XFC_BIG.result), c(1.8, 35.9, 18.7, 59.7))
})

test_that('Checking XFC_NAT_EMAP.result', {
  expect_equal(as.vector(habitatmet$XFC_NAT_EMAP.result), c(12.2, 40.9, 28.2, 68.3))
})

test_that('Checking XFC_NAT_SWAMP.result', {
  expect_equal(as.vector(habitatmet$XFC_NAT_SWAMP.result), c(67.9, 52.2, 31.8, 76.9))
})

test_that('Checking CFC_AQM.result', {
  expect_equal(as.vector(habitatmet$CFC_AQM.result), c(11, 10, 2, 10))
})

test_that('Checking CFC_HUM.result', {
  expect_equal(as.vector(habitatmet$CFC_HUM.result), c(0, 5, 0, 11))
})

test_that('Checking CFC_RCK.result', {
  expect_equal(as.vector(habitatmet$CFC_RCK.result), c(0, 11, 11, 11))
})

test_that('Checking CFC_ALG.result', {
  expect_equal(as.vector(habitatmet$CFC_ALG.result), c(2, 3, 4, 11))
})

test_that('Checking CFC_LWD.result', {
  expect_equal(as.vector(habitatmet$CFC_LWD.result), c(0, 0, 3, 10))
})

test_that('Checking CFC_LTR.result', {
  expect_equal(as.vector(habitatmet$CFC_LTR.result), c(9, 11, 6, 9))
})

test_that('Checking CFC_OHV.result', {
  expect_equal(as.vector(habitatmet$CFC_OHV.result), c(11, 10, 7, 11))
})

test_that('Checking CFC_BRS.result', {
  expect_equal(as.vector(habitatmet$CFC_BRS.result), c(4, 10, 10, 11))
})

test_that('Checking CFC_UCB.result', {
  expect_equal(as.vector(habitatmet$CFC_UCB.result), c(4, 11, 3, 10))
})

test_that('Checking CFC_ALL_EMAP.result', {
  expect_equal(as.vector(habitatmet$CFC_ALL_EMAP.result), c(5, 7, 7, 8))
})

test_that('Checking CFC_ALL_SWAMP.result', {
  expect_equal(as.vector(habitatmet$CFC_ALL_SWAMP.result), c(6, 8, 8, 9))
})

test_that('Checking XFC_BIG.count', {
  expect_equal(as.vector(habitatmet$XFC_BIG.count), c(4, 4, 4, 4))
})

test_that('Checking XFC_BIG3.result', {
  expect_equal(as.vector(habitatmet$XFC_BIG3.result), c(1.8, 30, 18.7, 54.7))
})

test_that('Checking XFC_BIG3.count', {
  expect_equal(as.vector(habitatmet$XFC_BIG3.count), c(3, 3, 3, 3))
})

test_that('Checking XFC_NAT_EMAP.count', {
  expect_equal(as.vector(habitatmet$XFC_NAT_EMAP.count), c(5, 5, 5, 5))
})

test_that('Checking XFC_NAT_SWAMP.count', {
  expect_equal(as.vector(habitatmet$XFC_NAT_SWAMP.count), c(7, 7, 7, 7))
})

test_that('Checking CFC_ALL_EMAP.count', {
  expect_equal(as.vector(habitatmet$CFC_ALL_EMAP.count), c(8, 8, 8, 8))
})

test_that('Checking CFC_ALL_SWAMP.count', {
  expect_equal(as.vector(habitatmet$CFC_ALL_SWAMP.count), c(9, 9, 9, 9))
})

test_that('Checking H_AqHab.result', {
  expect_equal(as.vector(habitatmet$H_AqHab.result), c(0.89, 1.73, 1.63, 1.6))
})

test_that('Checking H_AqHab_mod1.result', {
  expect_equal(as.vector(habitatmet$H_AqHab_mod1.result), c(0.32, 0.33, 0.22, 0.52))
})

test_that('Checking H_AqHab.count', {
  expect_equal(as.vector(habitatmet$H_AqHab.count), c(6, 7, 8, 8))
})

test_that('Checking Ev_AqHab.result', {
  expect_equal(as.vector(habitatmet$Ev_AqHab.result), c(0.5, 0.89, 0.78, 0.77))
})

test_that('Checking Ev_AqHab.count', {
  expect_equal(as.vector(habitatmet$Ev_AqHab.count), c(6, 7, 8, 8))
})

test_that('Checking CFC_ALG.count', {
  expect_equal(as.vector(habitatmet$CFC_ALG.count), c(11, 11, 11, 11))
})

test_that('Checking CFC_AQM.count', {
  expect_equal(as.vector(habitatmet$CFC_AQM.count), c(11, 11, 11, 11))
})

test_that('Checking CFC_BRS.count', {
  expect_equal(as.vector(habitatmet$CFC_BRS.count), c(11, 11, 11, 11))
})

test_that('Checking CFC_HUM.count', {
  expect_equal(as.vector(habitatmet$CFC_HUM.count), c(11, 11, 11, 11))
})

test_that('Checking CFC_LTR.count', {
  expect_equal(as.vector(habitatmet$CFC_LTR.count), c(11, 11, 11, 11))
})

test_that('Checking CFC_LWD.count', {
  expect_equal(as.vector(habitatmet$CFC_LWD.count), c(11, 11, 11, 11))
})

test_that('Checking CFC_OHV.count', {
  expect_equal(as.vector(habitatmet$CFC_OHV.count), c(11, 11, 11, 11))
})

test_that('Checking CFC_RCK.count', {
  expect_equal(as.vector(habitatmet$CFC_RCK.count), c(11, 11, 11, 11))
})

test_that('Checking CFC_UCB.count', {
  expect_equal(as.vector(habitatmet$CFC_UCB.count), c(11, 11, 11, 11))
})

test_that('Checking Rich_AqHab.result', {
  expect_equal(as.vector(habitatmet$Rich_AqHab.result), c(5, 6, 7, 7))
})

test_that('Checking Rich_AqHab.count', {
  expect_equal(as.vector(habitatmet$Rich_AqHab.count), c(11, 11, 11, 11))
})

