# Golden-value regression tests for bankmorph().
# Generated by tools/generate_golden_tests.R -- regenerate rather than hand-editing.
# Expected values are the confirmed-correct output for `sampdat` as of 2026-08-20.

test_that('bankmorph() returns the expected samples in the expected order', {
  expect_equal(rownames(bankmorphmet), c('105PS0231_2013-08-29_DFW-ABL', '205PS0202_2013-07-17_MPSL-DFW', '308PS0204_2013-05-21_DFW-ABL', '520PS0455_2013-07-22_MPSL-DFW'))
})

test_that('bankmorph() returns the expected columns', {
  expect_equal(colnames(bankmorphmet), c('XBKF_H.result', 'XBKF_H.count', 'XBKF_H.sd', 'XBKF_W.result', 'XBKF_W.count', 'XBKF_W.sd', 'XWDEPTH.result', 'XWDEPTH.count', 'XWDEPTH.sd', 'XWIDTH.result', 'XWIDTH.count', 'XWIDTH.sd', 'XWDR.result', 'XWDR.count', 'XWDA.result', 'XWDA.count', 'XWDM.count', 'XWDM.result', 'XWDM.sd', 'XBKF_TH.result', 'XBKF_TH.count', 'XBKF_DA.result', 'XBKF_DA.count'))
})

test_that('Checking XBKF_H.result', {
  expect_equal(as.vector(bankmorphmet$XBKF_H.result), c(0.8, 0.2, 1.2, 0.3))
})

test_that('Checking XBKF_H.count', {
  expect_equal(as.vector(bankmorphmet$XBKF_H.count), c(11, 11, 11, 11))
})

test_that('Checking XBKF_H.sd', {
  expect_equal(as.vector(bankmorphmet$XBKF_H.sd), c(0.1, 0.06, 0.44, 0))
})

test_that('Checking XBKF_W.result', {
  expect_equal(as.vector(bankmorphmet$XBKF_W.result), c(21, 3.4, 22.2, 30.2))
})

test_that('Checking XBKF_W.count', {
  expect_equal(as.vector(bankmorphmet$XBKF_W.count), c(11, 11, 11, 11))
})

test_that('Checking XBKF_W.sd', {
  expect_equal(as.vector(bankmorphmet$XBKF_W.sd), c(7.4, 0.55, 7.31, 7.43))
})

test_that('Checking XWDEPTH.result', {
  expect_equal(as.vector(bankmorphmet$XWDEPTH.result), c(41.8, 6.8, 18.6, 29.8))
})

test_that('Checking XWDEPTH.count', {
  expect_equal(as.vector(bankmorphmet$XWDEPTH.count), c(105, 105, 105, 105))
})

test_that('Checking XWDEPTH.sd', {
  expect_equal(as.vector(bankmorphmet$XWDEPTH.sd), c(36.16, 8.01, 18.65, 43.73))
})

test_that('Checking XWIDTH.result', {
  expect_equal(as.vector(bankmorphmet$XWIDTH.result), c(15.5, 2.4, 10.7, 26.9))
})

test_that('Checking XWIDTH.count', {
  expect_equal(as.vector(bankmorphmet$XWIDTH.count), c(21, 21, 21, 21))
})

test_that('Checking XWIDTH.sd', {
  expect_equal(as.vector(bankmorphmet$XWIDTH.sd), c(4.03, 0.64, 3, 7.49))
})

test_that('Checking XWDR.result', {
  expect_equal(as.vector(bankmorphmet$XWDR.result), c(37.0813397129187, 35.2941176470588, 57.5268817204301, 90.2684563758389))
})

test_that('Checking XWDR.count', {
  expect_equal(as.vector(bankmorphmet$XWDR.count), c(21, 21, 21, 21))
})

test_that('Checking XWDA.result', {
  expect_equal(as.vector(bankmorphmet$XWDA.result), c(0.269677419354839, 0.283333333333333, 0.173831775700935, 0.110780669144981))
})

test_that('Checking XWDA.count', {
  expect_equal(as.vector(bankmorphmet$XWDA.count), c(105, 105, 105, 105))
})

test_that('Checking XWDM.count', {
  expect_equal(as.vector(bankmorphmet$XWDM.count), c(21, 21, 21, 21))
})

test_that('Checking XWDM.result', {
  expect_equal(as.vector(bankmorphmet$XWDM.result), c(79.8, 14.7, 40.1, 77))
})

test_that('Checking XWDM.sd', {
  expect_equal(as.vector(bankmorphmet$XWDM.sd), c(15.3, 9, 14.9, 53.2))
})

test_that('Checking XBKF_TH.result', {
  expect_equal(as.vector(bankmorphmet$XBKF_TH.result), c(1.6, 0.3, 1.6, 1.1))
})

test_that('Checking XBKF_TH.count', {
  expect_equal(as.vector(bankmorphmet$XBKF_TH.count), c(11, 11, 11, 11))
})

test_that('Checking XBKF_DA.result', {
  expect_equal(as.vector(bankmorphmet$XBKF_DA.result), c(33.6, 1.2, 35.5, 32.3))
})

test_that('Checking XBKF_DA.count', {
  expect_equal(as.vector(bankmorphmet$XBKF_DA.count), c(11, 11, 11, 11))
})

