# Generates golden-value regression tests for every exported metric function.
#
# The expected values are whatever the current code produces for the bundled
# `sampdat` sample. They are a regression baseline, not an independent
# calculation: they lock the output so an unintended change becomes a test
# failure. If a change legitimately moves a value, re-run this script and
# explain the diff (see AGENTS.md).
#
# Usage, from the repo root:
#   Rscript tools/generate_golden_tests.R
#
# test_substrate.R is deliberately NOT regenerated -- it is hand-maintained
# and carries skip()s for the unresolved SB_*_D25/D75/D90 percentile issue.

suppressMessages(suppressWarnings(devtools::load_all(".", quiet = TRUE)))

testdir <- "tests/testthat"

# metric function -> object name used in helper_object.R
metrics <- c(
  algae            = "algaemet",
  bankmorph        = "bankmorphmet",
  bankstability    = "bankstabilitymet",
  channelmorph     = "channelmorphmet",
  channelsinuosity = "channelsinuositymet",
  densiometer      = "densiometermet",
  disturbance      = "disturbancemet",
  flow             = "flowmet",
  habitat          = "habitatmet",
  misc             = "miscmet",
  quality          = "qualitymet",
  ripveg           = "ripvegmet",
  substrate        = "submet"
)

# render a vector as R source that expect_equal() can consume
as_src <- function(x) {
  x <- as.vector(x)
  # NA must carry the column's type: a bare NA is logical, which makes
  # expect_equal() fail on type against an all-NA numeric column.
  na_lit <- switch(typeof(x),
    double    = "NA_real_",
    integer   = "NA_integer_",
    character = "NA_character_",
    "NA"
  )
  if (is.character(x)) {
    return(paste0("c(", paste(ifelse(is.na(x), na_lit, paste0("'", x, "'")),
                              collapse = ", "), ")"))
  }
  out <- vapply(x, function(v) {
    if (is.nan(v)) return("NaN")
    if (is.na(v)) return(na_lit)
    if (is.infinite(v)) return(if (v > 0) "Inf" else "-Inf")
    format(v, digits = 15, trim = TRUE, scientific = FALSE)
  }, character(1))
  paste0("c(", paste(out, collapse = ", "), ")")
}

# matrices need [, "col"]; data frames use $col
accessor <- function(obj, res, col) {
  if (is.matrix(res)) sprintf('%s[, "%s"]', obj, col) else sprintf("%s$%s", obj, col)
}

# ---- helper_object.R: compute each metric set once for the whole suite -------

helper <- c(
  "# Generated by tools/generate_golden_tests.R -- edit that script, not this file.",
  "# Each metric set is computed once here and reused by the test_*.R files.",
  "",
  "sampdat <- phabformat(sampdat)",
  ""
)
for (fn in names(metrics)) {
  helper <- c(helper, sprintf("%s <- suppressWarnings(%s(sampdat))", metrics[[fn]], fn))
}
writeLines(helper, file.path(testdir, "helper_object.R"))

# ---- one test file per metric function ---------------------------------------

for (fn in names(metrics)) {

  if (fn == "substrate") next  # hand-maintained, see note above

  obj <- metrics[[fn]]
  res <- suppressWarnings(get(fn)(phabformat(sampdat)))

  lines <- c(
    sprintf("# Golden-value regression tests for %s().", fn),
    "# Generated by tools/generate_golden_tests.R -- regenerate rather than hand-editing.",
    "# Expected values are the confirmed-correct output for `sampdat` as of 2026-08-20.",
    "",
    sprintf("test_that('%s() returns the expected samples in the expected order', {", fn),
    sprintf("  expect_equal(rownames(%s), %s)", obj, as_src(rownames(res))),
    "})",
    "",
    sprintf("test_that('%s() returns the expected columns', {", fn),
    sprintf("  expect_equal(colnames(%s), %s)", obj, as_src(colnames(res))),
    "})",
    ""
  )

  for (col in colnames(res)) {
    val <- if (is.matrix(res)) res[, col] else res[[col]]
    lines <- c(
      lines,
      sprintf("test_that('Checking %s', {", col),
      sprintf("  expect_equal(as.vector(%s), %s)", accessor(obj, res, col), as_src(val)),
      "})",
      ""
    )
  }

  writeLines(lines, file.path(testdir, sprintf("test_%s.R", fn)))
  cat(sprintf("wrote test_%s.R (%d columns)\n", fn, ncol(res)))
}

# ---- end-to-end phabmetrics() test ------------------------------------------

alldat <- suppressWarnings(phabmetrics(sampdat))
alldat <- alldat[order(alldat$StationCode, alldat$Variable), ]

lines <- c(
  "# End-to-end golden-value test for phabmetrics(), the documented top-level check.",
  "# Generated by tools/generate_golden_tests.R -- regenerate rather than hand-editing.",
  "# Expected values are the confirmed-correct output for `sampdat` as of 2026-08-20.",
  "",
  "# phabmetrics() is run here rather than in the helper because it takes the raw",
  "# sampdat, while helper_object.R overwrites sampdat with its formatted version.",
  "allmet <- suppressWarnings(phabmetrics(PHABMetrics::sampdat))",
  "allmet <- allmet[order(allmet$StationCode, allmet$Variable), ]",
  "",
  "test_that('phabmetrics() returns the expected shape', {",
  sprintf("  expect_equal(nrow(allmet), %d)", nrow(alldat)),
  sprintf("  expect_equal(colnames(allmet), %s)", as_src(colnames(alldat))),
  "})",
  "",
  "test_that('phabmetrics() returns the expected station/variable grid', {",
  sprintf("  expect_equal(unique(allmet$StationCode), %s)", as_src(unique(alldat$StationCode))),
  sprintf("  expect_equal(sort(unique(allmet$Variable)), %s)", as_src(sort(unique(alldat$Variable)))),
  "})",
  ""
)

# every Result, keyed by station+variable, so any drift points at a row
lines <- c(
  lines,
  "test_that('phabmetrics() Result values match the golden baseline', {",
  sprintf("  expect_equal(as.vector(allmet$Result), %s)", as_src(alldat$Result)),
  "})",
  ""
)

# the PCT_* subset documented in AGENTS.md, called out explicitly
vars <- c("PCT_CF", "PCT_DR", "PCT_GL", "PCT_POOL", "PCT_RA", "PCT_RI",
          "PCT_RN", "PCT_FAST", "PCT_SLOW")
sub <- alldat[alldat$Variable %in% vars, ]
lines <- c(
  lines,
  "test_that('phabmetrics() flow/substrate PCT_* metrics match the AGENTS.md table', {",
  sprintf("  pct <- allmet[allmet$Variable %%in%% %s, ]", as_src(vars)),
  sprintf("  expect_equal(paste(pct$StationCode, pct$Variable), %s)",
          as_src(paste(sub$StationCode, sub$Variable))),
  sprintf("  expect_equal(as.vector(pct$Result), %s)", as_src(sub$Result)),
  "})",
  ""
)

writeLines(lines, file.path(testdir, "test_phabmetrics.R"))
cat(sprintf("wrote test_phabmetrics.R (%d rows)\n", nrow(alldat)))
